version: "3.9"

services:

  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.artifacts/db:/data/db
    networks:
      - joker_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - joker_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - joker_network

networks:
  joker_network:
    name: joker_network