FROM python:3.8

WORKDIR /harvest

RUN mkdir /etc/harvest/

ADD secrets.yaml /etc/harvest/secrets.yaml

ADD /requirements.txt ./requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

ADD . .

CMD ["python3", "harvest.py"]
